"""Split each multi-panel pit-stop PNG into individual subplot PNGs.

The existing combined images were generated by visualize.py as 2x2 or
1x3 matplotlib grids.  This utility detects the white gutters between
sub-axes, then crops each sub-axis to its own PNG sized for solo
inclusion in the LaTeX report.

Per-file output naming uses a letter suffix (a/b/c/d) matching the
subplot label in the original combined image.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
from PIL import Image

REPO_ROOT  = Path(__file__).resolve().parents[2]
PLOTS_DIR  = REPO_ROOT / "outputs" / "pit_stop_strategy" / "plots"

# Each entry tells the splitter
#   - the grid layout (rows, cols)
#   - the output filenames in row-major order (a, b, c, d…)
# Files not listed are skipped (so the combined PNGs can co-exist).
LAYOUTS = {
    "01_dataset_overview.png": {
        "grid": (2, 2),
        "outs": ["01a_laptime_compound.png",
                 "01b_tyre_life_dist.png",
                 "01c_pitstop_lap_dist.png",
                 "01d_pit_rate_season.png"],
    },
    "02_tyre_analysis.png": {
        "grid": (2, 2),
        "outs": ["02a_tyre_decay_compound.png",
                 "02b_tyre_life_at_pit.png",
                 "02c_pitlap_heatmap.png",
                 "02d_stint_length.png"],
    },
    "03_model_outputs.png": {
        "grid": (2, 2),
        "outs": ["03a_pred_prob_dist.png",
                 "03b_roc_curve.png",
                 "03c_pr_curve.png",
                 "03d_calibration.png"],
    },
    "04_team_strategy.png": {
        "grid": (1, 3),
        "outs": ["04a_risk_scatter.png",
                 "04b_team_tyrelife_box.png",
                 "04c_compound_mix_heatmap.png"],
        # Heatmap's adjacent colorbar confuses gutter detection; force uniform.
        "uniform": True,
    },
    "05_race_dynamics.png": {
        "grid": (2, 2),
        "outs": ["05a_position_changes.png",
                 "05b_pit_prob_progress.png",
                 "05c_pit_compound_season.png",
                 "05d_pit_prob_heatmap.png"],
    },
    "06_feature_analysis.png": {
        "grid": (2, 2),
        "outs": ["06a_corr_matrix.png",
                 "06b_feature_violin.png",
                 "06c_traffic_pit_prob.png",
                 "06d_pace_decay_compound.png"],
    },
    "07_stochastic_analysis.png": {
        "grid": (2, 2),
        "outs": ["07a_hazard_rate.png",
                 "07b_pace_decay_hist.png",
                 "07c_cox_vs_bilstm.png",
                 "07d_vsc_pit_prob.png"],
    },
}

# Heuristics for gutter detection
WHITE_THRESH = 0.94      # pixel V >= this counts as "white"
GUTTER_FRAC  = 0.985     # row/col must be this fraction white to be a gutter
MIN_GUTTER_WIDTH = 8     # minimum gutter run in pixels
PAD_PX = 6               # padding around each crop


def _runs_of_true(mask: np.ndarray) -> list[tuple[int, int]]:
    """Return list of (start, end_exclusive) for runs of True in 1-D mask."""
    runs = []
    in_run = False
    start = 0
    for i, v in enumerate(mask):
        if v and not in_run:
            start = i
            in_run = True
        elif not v and in_run:
            runs.append((start, i))
            in_run = False
    if in_run:
        runs.append((start, len(mask)))
    return runs


def _detect_gutter_centres(arr: np.ndarray, axis: int,
                           skip_top: int = 0) -> list[int]:
    """Return centre indices of each non-trivial white gutter along axis.

    axis=0 -> horizontal gutters (slice between rows of subplots)
    axis=1 -> vertical   gutters (slice between cols of subplots)
    """
    # Min over RGB → darkness; pixel is "white" if max channel >= thresh
    rgb = arr[..., :3].astype(np.float32) / 255.0
    is_white = rgb.min(axis=-1) >= WHITE_THRESH

    if axis == 0:
        # fraction of white pixels per row
        frac = is_white.mean(axis=1)
        if skip_top:
            frac = frac.copy()
            frac[:skip_top] = 0.0
    else:
        frac = is_white.mean(axis=0)

    gutters = _runs_of_true(frac >= GUTTER_FRAC)
    gutters = [(s, e) for s, e in gutters if (e - s) >= MIN_GUTTER_WIDTH]
    return gutters


def _interior_gutter_centres(arr: np.ndarray, axis: int,
                             n_needed: int,
                             skip_top: int = 0) -> list[int]:
    """Pick the `n_needed` longest gutters that lie in the interior
    (excluding any gutter touching the outer edge) and return their centres.
    """
    runs = _detect_gutter_centres(arr, axis=axis, skip_top=skip_top)
    dim = arr.shape[axis]

    interior = [(s, e) for s, e in runs
                if s > dim * 0.04 and e < dim * 0.96]

    if len(interior) < n_needed:
        # fall back: use all runs (including edges)
        interior = runs

    # Sort by run length (longest first), keep n_needed
    interior.sort(key=lambda r: (r[1] - r[0]), reverse=True)
    chosen = sorted(interior[:n_needed], key=lambda r: r[0])
    return [(s + e) // 2 for s, e in chosen]


def split_image(in_path: Path, grid: tuple[int, int],
                out_names: list[str], uniform: bool = False) -> None:
    rows, cols = grid
    expected = rows * cols
    assert len(out_names) == expected, \
        f"need {expected} output names for {rows}x{cols} grid"

    im = Image.open(in_path).convert("RGBA")
    arr = np.array(im)
    h, w = arr.shape[:2]

    # Skip the top title strip when looking for horizontal gutters
    skip_top = int(h * 0.06)

    # Find interior gutter centres
    n_h = rows - 1
    n_v = cols - 1

    if uniform:
        h_centres = [int(skip_top + (h - skip_top) * (i + 1) / rows)
                     for i in range(n_h)]
        v_centres = [int(w * (i + 1) / cols) for i in range(n_v)]
    else:
        h_centres = _interior_gutter_centres(arr, axis=0, n_needed=n_h,
                                              skip_top=skip_top) if n_h else []
        v_centres = _interior_gutter_centres(arr, axis=1, n_needed=n_v) if n_v else []

        if len(h_centres) != n_h or len(v_centres) != n_v:
            # Fall back to uniform percentage split
            print(f"  [WARN] {in_path.name}: gutter detection partial — using uniform split")
            h_centres = [int(h * (i + 1) / rows) for i in range(n_h)]
            v_centres = [int(w * (i + 1) / cols) for i in range(n_v)]

    # Build row and column boundaries
    row_bounds = [skip_top] + h_centres + [h]
    col_bounds = [0] + v_centres + [w]

    idx = 0
    for r in range(rows):
        for c in range(cols):
            top, bot = row_bounds[r], row_bounds[r + 1]
            left, right = col_bounds[c], col_bounds[c + 1]

            # Add small padding inside the available canvas
            top = max(0, top - PAD_PX)
            bot = min(h, bot + PAD_PX)
            left = max(0, left - PAD_PX)
            right = min(w, right + PAD_PX)

            crop = arr[top:bot, left:right]
            out_path = PLOTS_DIR / out_names[idx]
            Image.fromarray(crop).save(out_path, optimize=True)
            print(f"  [saved] {out_names[idx]}  ({crop.shape[1]}x{crop.shape[0]})")
            idx += 1


def main() -> None:
    if not PLOTS_DIR.exists():
        print(f"No plots directory: {PLOTS_DIR}", file=sys.stderr)
        sys.exit(1)

    for combined_name, spec in LAYOUTS.items():
        path = PLOTS_DIR / combined_name
        if not path.exists():
            print(f"[skip] {combined_name} not found")
            continue
        print(f"\nSplitting {combined_name}")
        split_image(path, spec["grid"], spec["outs"],
                    uniform=spec.get("uniform", False))

    print("\nDone.")


if __name__ == "__main__":
    main()
